[project]
name = "asfes-multiplex"
version = "0.2.1"
requires-python = ">=3.11"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]

[tool.coverage.run]
source = ["server"]
omit = [
    "server/core/internal_data/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:",
    "raise NotImplementedError",
    "@abstractmethod",
]
fail_under = 80

[tool.coverage.html]
directory = "htmlcov"
