from __future__ import annotations

import base64
import os

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives import hashes


# Domain-separation label: uniquely scopes this key material to proxy password
# encryption. Changing this value invalidates all existing encrypted records.
_HKDF_INFO = b"asfes-multiplex:proxy-password-encryption:v1"


def _derive_key(secret: str) -> bytes:
    """Derive a 32-byte AES key from the proxy encryption secret via HKDF-SHA256.

    Using HKDF (RFC 5869) with an explicit ``info`` label ensures:
    - Domain separation: the derived key is cryptographically bound to *only*
      proxy password encryption and cannot be confused with any other key
      material (e.g. JWT signing).
    - Future-proofing: ``info`` includes a version tag so key format changes
      can be detected without breaking existing ciphertext.

    ``salt`` is left as ``None`` (HKDF treats this as all-zeros of hash
    length), which is correct when the input keying material is already a
    high-entropy secret string (as generated by ``secrets.token_urlsafe``).
    """
    kdf = HKDF(
        algorithm=hashes.SHA256(),
        length=32,
        salt=None,
        info=_HKDF_INFO,
    )
    return kdf.derive(secret.encode("utf-8"))


class ProxyEncryptor:
    """AES-256-GCM encryptor for proxy passwords.

    Requires a dedicated ``proxy_encryption_key`` secret — must **not** be
    the same value as ``api_jwt_secret``.  The key is derived via HKDF to
    enforce domain separation even if the caller accidentally passes the wrong
    secret.
    """

    def __init__(self, proxy_secret: str) -> None:
        self.key = _derive_key(proxy_secret)
        self.aesgcm = AESGCM(self.key)

    def encrypt(self, plaintext: str | None) -> str | None:
        if plaintext is None:
            return None
        iv = os.urandom(12)
        ciphertext = self.aesgcm.encrypt(iv, plaintext.encode("utf-8"), None)
        return base64.b64encode(iv + ciphertext).decode("utf-8")

    def decrypt(self, ciphertext_b64: str | None) -> str | None:
        if ciphertext_b64 is None:
            return None
        try:
            data = base64.b64decode(ciphertext_b64.encode("utf-8"))
            if len(data) < 12:
                raise ValueError("Invalid encrypted data length")
            iv = data[:12]
            ciphertext = data[12:]
            return self.aesgcm.decrypt(iv, ciphertext, None).decode("utf-8")
        except Exception as exc:
            raise ValueError(f"Decryption failed: {exc}") from exc
